In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sentiment_pbt_Feb26.csv')

In [3]:
df.head()

,Unnamed: 0,company_name,overall_scores,balance_scores,benefit_scores,security_scores,management_scores,culture_scores,former_current,lead,...,other_states,wa,all_text,text_neg_score,text_neu_score,text_pos_score,num_neg_score,num_neu_score,num_pos_score,final_pbt_sc
0,0,Google,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,1.0,0,...,1,0,I mean its GoogleI was a contractor so the onl...,0.038,0.705,0.257,0.0,0.0,1.0,0.6095
1,1,Google,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,1.0,0,...,1,0,I mean its GoogleManagement is not professiona...,0.000,0.766,0.234,0.0,0.0,1.0,0.6170
2,2,Google,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,1.0,0,...,1,0,I mean its GoogleI was a contractor so the onl...,0.038,0.705,0.257,0.0,0.0,1.0,0.6095
3,3,Google,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,1.0,0,...,1,0,I mean its GoogleManagement is not professiona...,0.000,0.766,0.234,0.0,0.0,1.0,0.6170
4,4,Google,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,width: 100%;,1.0,0,...,1,0,I mean its GoogleI was a contractor so the onl...,0.038,0.705,0.257,0.0,0.0,1.0,0.6095

In [4]:
df.groupby('company_name').final_pbt_sc.mean()

company_name
Adobe                0.425971
Airbnb               0.394000
Apple                0.384343
Boeing               0.390675
Cisco                0.355089
Dell                 0.321573
Expedia              0.224867
Google               0.340324
IBM                  0.200017
Indeed               0.378298
Intel                0.412966
JLL                  0.254017
KPMG                 0.253223
Kaiser Permanente    0.465540
Microsoft            0.392964
NOKIA                0.384591
Netflix              0.407536
Nordstrom            0.282991
Oracle               0.204458
Qualcomm             0.263159
Redfin               0.286315
Salesforce           0.491458
T-mobile             0.448775
Tableau             -0.000167
Tesla                0.260840
Texas Instrument     0.443759
Twitter              0.349042
Uber                 0.201444
Name: final_pbt_sc, dtype: float64